version: 0.2
env:
  parameter-store:
    AWS_ACCESS_KEY_ID: /CodeBuild/AwsAccessKey
    AWS_SECRET_ACCESS_KEY: /CodeBuild/AwsSecretAccessKey
    AWS_DEFAULT_REGION: /CodeBuild/AwsDefaultRegion
  variables:
    ENV_NAME: Dev
phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - echo Installing Serverless...
      - npm install -g serverless
  pre_build:
    commands:
      - echo Installing frontend NPM dependencies...
      - cd frontend && npm install
      - echo installing backend dependencies
      - cd ../backend && npm install
  build:
    commands:
      - echo Deployment started on `date`
      - echo Deploying with Serverless Framework
      - echo frontend build started
      - cd ../frontend && npm run build

cache:
  paths:
    - "frontend/node_modules/**/*"
    - "backend/node_modules/**/*"
